### ISSUE TITLE
installed with windows

### ISSUE THREAD

**Issue by Lagfree** [Alikhalkhali/programs-watcher#3]
Hey so I installed everything I think correctly but I just installed the tool and it's not showing up in my discord my only difference is I used windows to install it I'll try reinstalling it with Linux but it runs in docker if you can please help

**Comment by Alikhalkhali** [comment]
Hello! 
To install the tool on Windows, please follow this guide:

[Manual Installation Guide for Windows](https://github.com/Alikhalkhali/programs-watcher#option-2-manual-installation-recommended-for-desktop-and-laptop-usage)

Let me know if you need any further assistance. Thank you!

**Comment by Lagfree** [comment]
Yeah sorry I didn't know if you needed a response and I'm just seeing this
didn't see the message on github but I did install mongo db and I had to
reinstall the program  all the other steps worked out fine and now it works
perfectly thank you for following up man loving the program by the way
