### ISSUE TITLE
Integration With Telegram Bot

### ISSUE THREAD

**Issue by arshiaor** [Alikhalkhali/programs-watcher#4]
Hello, I was wondering if there is a way to use your tool with Telegram api instead of discord webhook?

**Comment by Alikhalkhali** [comment]
Hi Arshiaor
Thank you for the suggestion. In the upcoming v2 update, which will be released in a few weeks, this feature will be added. To stay informed about the update sooner, you can follow me on Twitter at ali_khalkhali0.
