### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by JoeWalker12** [Alikhalkhali/programs-watcher#5]
I am experiencing an issue with ProgramWatcher. The Program is Not working at all and Unfortunately, I'm unable to pinpoint the exact issue or its root cause.

**Comment by EthicalHumanoid** [comment]
The same thing is happening to me, I do everything as written in the manual from setting up requirements to pasting the discord webhook. I could even run the main.py but found no messages in the discord channel. Also, the main.py stopped working after 1st attempt. 
Btw thanks for this tool

**Comment by Alikhalkhali** [comment]
Hi JoeWalker12 and EthicalHumanoid,

Apologies for the delay in response. Thank you for letting us know. The issues have been resolved, and you can now proceed to use the service.

Additionally, there is an upcoming update that hopefully will make up for the delay. To stay informed about the update sooner, you can follow me on Twitter at ali_khalkhali0.
